# Generated by Django 6.1 on 2026-08-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "picture",
                    models.CharField(
                        default="https://www.google.com/imgres?q=restaurant%20hyderabad&imgurl=https%3A%2F%2Fwww.cathaypacific.com%2Fcontent%2Fdam%2Ffocal-point%2Fcx%2Finspiration%2F2025%2F01%2FThe_best_restaurants_and_bars_in_Hyderabad-Roast_CCx_Exterior-courtesyimages-1.renditionimage.900.900.jpg&imgrefurl=https%3A%2F%2Fwww.cathaypacific.com%2Fcx%2Fen_IN%2Finspiration%2Fdining%2Fhyderabad-dining-guide.html&docid=fVY6uQwC9i-8wM&tbnid=7brpRxbrJ5w0iM&vet=12ahUKEwiBxs2B46mWAxUcUGwGHRBaDREQnPAOegUI_AEQAA..i&w=900&h=900&hcb=2&ved=2ahUKEwiBxs2B46mWAxUcUGwGHRBaDREQnPAOegUI_AEQAA",
                        max_length=200,
                    ),
                ),
                ("cuisine", models.CharField(max_length=200)),
                ("rating", models.CharField(max_length=20)),
            ],
        ),
    ]
