# Generated by Django 6.1 on 2026-08-20 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0002_restaurant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="picture",
            field=models.URLField(
                default="https://www.google.com/imgres?q=restaurant%20hyderabad&imgurl=https%3A%2F%2Fwww.cathaypacific.com%2Fcontent%2Fdam%2Ffocal-point%2Fcx%2Finspiration%2F2025%2F01%2FThe_best_restaurants_and_bars_in_Hyderabad-Roast_CCx_Exterior-courtesyimages-1.renditionimage.900.900.jpg&imgrefurl=https%3A%2F%2Fwww.cathaypacific.com%2Fcx%2Fen_IN%2Finspiration%2Fdining%2Fhyderabad-dining-guide.html&docid=fVY6uQwC9i-8wM&tbnid=7brpRxbrJ5w0iM&vet=12ahUKEwiBxs2B46mWAxUcUGwGHRBaDREQnPAOegUI_AEQAA..i&w=900&h=900&hcb=2&ved=2ahUKEwiBxs2B46mWAxUcUGwGHRBaDREQnPAOegUI_AEQAA"
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="rating",
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=200)),
                ("price", models.FloatField()),
                ("vegeterian", models.BooleanField(default=False)),
                (
                    "picture",
                    models.URLField(
                        default="https://www.google.com/imgres?q=biryani&imgurl=https%3A%2F%2Fministryofcurry.com%2Fwp-content%2Fuploads%2F2024%2F06%2Fchicken-biryani-5-500x500.jpg&imgrefurl=https%3A%2F%2Fministryofcurry.com%2Fchicken-biryani%2F&docid=tKGBMlcvTWsu1M&tbnid=RXZqyM2A-_EYzM&vet=12ahUKEwiDwNP6sq-WAxVVT2wGHcnlInUQnPAOegQINhAA..i&w=500&h=500&hcb=2&ved=2ahUKEwiDwNP6sq-WAxVVT2wGHcnlInUQnPAOegQINhAA",
                        max_length=400,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="delivery.restaurant",
                    ),
                ),
            ],
        ),
    ]
