# Generated by Django 6.1 on 2026-08-22 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0003_alter_restaurant_picture_alter_restaurant_rating_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart",
                        to="delivery.customer",
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(related_name="carts", to="delivery.item"),
                ),
            ],
        ),
    ]
